name: pairing
version: '0.1.0.0'
author: Stephen Diehl
license: MIT
dependencies:
- base ==4.9.*
- protolude ==0.1.*
- QuickCheck >=2.9
- pretty-show >=1.6
- bytestring >=0.10
- cryptonite >=0.21
- memory >=0.14.1
library:
  exposed-modules:
  - Params
  - Fq
  - Fr
  - Fq2
  - Fq6
  - Fq12
  - Point
  - Group
  - Pairing
  - Test
